; PlatformIO Project Configuration File for µPhotoFrame
; Based on: https://github.com/pixelEDI/reterminal-e1002-epaper

[platformio]
src_dir = firmware/src

[env:seeed_xiao_esp32s3]
platform = espressif32
board = seeed_xiao_esp32s3
framework = arduino
monitor_speed = 115200
; Ports für Windows - bitte anpassen falls nötig
; upload_port = COM3
; monitor_port = COM3
lib_deps =
    zinggjm/GxEPD2 @ ^1.6.5
    bblanchon/ArduinoJson @ ^7.0.0