; PlatformIO Project Configuration File for microPhotoFrame
; Based on: https://github.com/pixelEDI/reterminal-e1002-epaper

[env:seeed_xiao_esp32s3]
platform = espressif32
board = seeed_xiao_esp32s3
framework = arduino
monitor_speed = 115200
; Ports fuer Windows - bitte anpassen falls noetig
; upload_port = COM3
; monitor_port = COM3
build_flags =
    -D PNG_MAX_BUFFERED_PIXELS=((801*4+1)*2)
lib_deps =
    zinggjm/GxEPD2 @ ^1.6.5
    bblanchon/ArduinoJson @ ^7.0.0
    bitbank2/PNGdec @ ^1.1.0
